include: ["assets", "bootstrap"]
exclude: ["Gemfile", ".git*", "*.org", "*.muse", "submodules", ".org-timestamps"]
title:
  ja: Youhei SASAKI's official site
  en: Youhei SASAKI's official site
email: uwabami@gfd-dennou.org
description:
  ja: "Youhei SASAKI's official site. My Interest: Fluid Dynamics, Convection, MHD Dynamo, Numerical Computing, Unix, Linux, Debian"
  en: "Youhei SASAKI's official site. My Interest: Fluid Dynamics, Convection, MHD Dynamo, Numerical Computing, Unix, Linux, Debian"
index:
  ja: index.html
  en: index.en.html
base: https://uwabami.github.io/
repository: uwabami/uwabami.github.io
twitter_username: uwabami
github_username:  uwabami
sass:
    style: compressed
gems:
  - jekyll-github-metadata
